name: Python linter
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ricardochaves/python-lint@v1.1.0
    with:
      use-pylint: false
      use-pycodestyle: true
      use-flake8: true
      use-black: true
      use-mypy: false
      use-isort: true
      extra-black-options: "-l 78"
